### ISSUE TITLE
feature req: support complex pattern

### ISSUE THREAD

**Issue by obar1** [seachicken/vscode-pomodoro-edit#4]
hi  @seachicken 
what about adding more flexibility to the supported pattern?
ex1
```
- [x] [p25-p5] wipp
```
would show 
![image](https://user-images.githubusercontent.com/387386/117396631-a2b8a900-aefa-11eb-8040-80dc7aefd2d1.png)
this
as usual
then after 25 minutes when the pomodoro expires
would change showing a 5 minutes bar

> you can easily parse this too allowing better flexibility
ex2
```
- [x] [p25-p5p25-p5p25-p525-p15] wipp
```
4 pomodoros 5 min breaks and long breaks
ex https://www.youtube.com/watch?v=jyQ8X_2rg40

**Comment by seachicken** [comment]
Thank you for your suggestions
It was published in v2.0.0 now

Supported complex pattern
e.g.
```
- [ ] [p25 p5 p25 p5 p25 p5] wipp
- [ ] [p25p5p25p5p25p5] wipp
- [ ] [(p25 p5)3] wipp
```
